on: 
  pull_request:
    types: [closed]

name: Deploy to npm
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.17
      uses: actions/setup-node@v1
      with:
        node-version: 10.17
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install Dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: Build Library
      run: npm run-script build
    - name: Test
      run: npm run-script test
    - name: Generate Coverage Badges
      run: npm run-script test:badges
    - name: Deploy to npm 🚀
      id: deploystep
      uses: benwinding/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Write comment
      uses: fastlane/github-actions/communicate-on-pull-request-merged@master
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-comment: "Deployed to npm! as version:${{steps.deploystep.outputs.version}}"
        pr-label-to-remove: ''        
